name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build ./app -t your-dockerhub-username/your-repo-name:latest

      - name: Push the Docker image
        run: docker push your-dockerhub-username/your-repo-name:latest


# name: Docker Login
# on:
#   # Trigger on events like:
#   push:
#     branches:
#       - main  # Or your primary branch
#   workflow_dispatch:  # Allow manual triggering

# jobs:
#   login:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           registry: docker.io  # Optional, defaults to Docker Hub
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
